services:
  app:
    image: jalenmakdocker/kermonix:latest
    container_name: kermonix-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kermonix-net

  db:
    image: postgres:16
    container_name: kermonix-db
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kermonix-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kermonix-net

  adminer:
    image: adminer
    container_name: kermonix-db-adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8060}:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kermonix-net

networks:
  kermonix-net:

volumes:
  kermonix-data:
